CUDA_VISIBLE_DEVICES: 0,1,2

data_process:
  
  training:
    patch_size: 48
    stride: 6
  test:
    patch_size: 48
    stride: 6


data_set: 
  path: /home/lwt/data_pro/vessel
  name: DRIVE

########### data_loader: #############
batch_size: 256

model:
  type: MAA_Net
  args:

    {}

loss:
  type: CE_DiceLoss
  args:

    {}

optimizer:
  type: Adam
  args:
    lr: 1e-4
    weight_decay: 1e-5

lr_scheduler:

  type: CosineAnnealingLR
  args:
    T_max: 40


###########   trainer: ##############
epochs: 1
save_dir: saved/
save_period: 1
tensorboard: true

log_dir: saved/runs
threshold: 0.5
amp: false
